### ISSUE TITLE
无法在浏览器中直接使用

### ISSUE THREAD

**Issue by rao2357** [linonetwo/segmentit#14]
我在html中引入了 https://cdn.jsdelivr.net/npm/segmentit@2.0.3/dist/umd/segmentit.js 后，使用文档中提供的代码，提示我Segmentit没有定义，是哪一步出错了呢😂。

**Comment by linonetwo** [comment]
看开发者工具，引入成功了吗？

**Comment by rao2357** [comment]
是的，导入成功了，我是在html中用script标签导入的该文件，可是无法直接使用该类，是使用方法错误了吗🤣
![image](https://user-images.githubusercontent.com/66585023/229692280-3d125e1a-7025-41f0-ba64-b3cb8c5dd46f.png)

**Comment by linonetwo** [comment]
之前有人问过，不过我也没试过 https://github.com/linonetwo/segmentit/issues/8

现在一般都是 pnpm 安装了，script 标签我从学前端开始就很少用过。

**Comment by aoweisi** [comment]
这个链接存在问题 建议修正为 https://cdn.jsdelivr.net/npm/segmentit@2.0.3/dist/umd/segmentit.min.js 即可使用

**Comment by linonetwo** [comment]
原来是这样，我改改 readme
