### ISSUE TITLE
Crash on strange queries

### ISSUE THREAD

**Issue by valdrox** [linonetwo/segmentit#5]
嗨！ 

有时候比较奇怪的text会让segmentit crash。

例如： 
```
const { Segment, useDefault, enPOSTag } = require("segmentit");
const segmentit = useDefault(new Segment());

const text = "分类：1946年出生在世人物美国总统美国总统候选人唐纳·川普内阁唐纳·川普美国企业家美国亿万富豪美国非虚构作品作家美国电视主持人飞黄腾达美国共和党总统候选人2016年美国总统选举候选人商人出身的总统右翼民粹主义福坦莫大学校友宾夕法尼亚大学沃顿商学院校友皇后区出身人物德国裔美国人苏格兰裔美国人现任国家领导人美国房地产商二十世纪美国企业家美国投资者美国电影男演员美国男作家美国政治作家暗杀未遂倖存者纽约州共和党人曼哈顿人2020年美国总统选举川普高地";
const test = segmentit.doSegment(failure);
```
Browser 会挡住。

有没有办法调整throw error吗？要不然，有没有办法先check string？

Thanks for making this!

**Comment by linonetwo** [comment]
是不是因为太长了内存占用过大 chrome 崩溃了？

**Comment by valdrox** [comment]
谢谢你的回复！我也觉得是长的问题。后来发现是这个issue ： https://github.com/leizongmin/node-segment/issues/6

我现在的问题是：有没有肯定是安全的长度(为了一般的 desktop browser)？ string.length <= 25? 

如果里面有英文和标点符号，会影响到吗？

**Comment by linonetwo** [comment]
你可以试试换换行

https://github.com/linonetwo/segmentit/blob/925c2ece9e3274b620d5caf408f9a05b3dbccdc8/src/Segment.js#L187-L189

因为这用的算法比较简单，所以效率大概是 O(文本长度 x 分词模块数量 x 模块词典大小) ，具体咋样只能二分法做做实验估计啦，你可以试试反馈在这供后人参考。
