### ISSUE TITLE
浏览器环境下如何引入分词工具呢？

### ISSUE THREAD

**Issue by iqiancheng** [linonetwo/segmentit#8]
浏览器或者油猴脚本，chrome extension 中如何应用此分词工具？
如果有个示例就好了，后端开发不是很熟悉，见谅啊

**Comment by linonetwo** [comment]
我理解的浏览器环境就是先 npm i 然后 webpack 打包那样。

如果你想用 script 标签来引入的话，那我也没试过，可能可以看看 unpkg 给出的 js 链接，不过我可能没支持这种引入方法。

**Comment by hardylab** [comment]
> 我理解的浏览器环境就是先 npm i 然后 webpack 打包那样。
> 
> 如果你想用 script 标签来引入的话，那我也没试过，可能可以看看 unpkg 给出的 js 链接，不过我可能没支持这种引入方法。

若是能支持一下  script  标签引入，就太好了。

**Comment by aoweisi** [comment]
这个链接存在问题 建议修正为 https://cdn.jsdelivr.net/npm/segmentit@2.0.3/dist/umd/segmentit.min.js 即可使用

**Comment by linonetwo** [comment]
谢了，加到 readme 了 https://github.com/linonetwo/segmentit/blob/master/README.md#install 应该是这样吧…

**Comment by linonetwo** [comment]
其实既然要联网了，个人建议还是调在线 API ，例如 openai 的 ada 或 Hugging face 的 transformer ，多省流量呀

**Comment by aoweisi** [comment]
很多问浏览器使用场景的 其实是 油猴扩展或做插件 js引入反而更方便
